# Generated by Django 4.2.3 on 2023-10-19 03:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('body', tinymce.models.HTMLField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='blog_photo/')),
            ],
        ),
    ]
