# Generated by Django 4.2.3 on 2023-10-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmodel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='blog_photo/'),
        ),
    ]
