# Generated by Django 4.2.3 on 2023-10-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentGatewaySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.CharField(blank=True, max_length=500, null=True)),
                ("store_pass", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "PaymentGatewaySetting",
                "verbose_name_plural": "PaymentGatewaySettings",
                "db_table": "paymentgatewaysettings",
            },
        ),
        migrations.CreateModel(
            name="UserInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("mobile", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=10)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
