# Generated by Django 4.2.3 on 2023-10-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinformation",
            name="timestamp",
            field=models.DateField(auto_now_add=True),
        ),
    ]
