# Generated by Django 4.2.3 on 2023-10-20 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_userinformation_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='role',
        ),
    ]
